/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubmissionId = IDL.Nat;
export const Submission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'projectDetails' : IDL.Text,
});

export const idlService = IDL.Service({
  'getSubmission' : IDL.Func([SubmissionId], [IDL.Opt(Submission)], ['query']),
  'listSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [SubmissionId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubmissionId = IDL.Nat;
  const Submission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'projectDetails' : IDL.Text,
  });
  
  return IDL.Service({
    'getSubmission' : IDL.Func(
        [SubmissionId],
        [IDL.Opt(Submission)],
        ['query'],
      ),
    'listSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [SubmissionId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };